FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# diegmer

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json; charset=utf-8)

        {"message": "Hello World!"}
